--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WolfDen133/ServerSettingsAPI
build-by-default: true
branches:
- main
projects:
  ServerSettingsAPI:
    path: ""
    model: virion
    type: library
...
